version: '3.4'
services:
  passbolt:
    build:
      context: .
      args:
        PECL_PASSBOLT_EXTENSIONS: "redis gnupg xdebug"
    env_file:
      - env/passbolt.env
    volumes:
      - gpg_volume:/var/www/passbolt/config/gpg
      - images_volume:/var/www/passbolt/webroot/img/public/images
    command: ["/usr/bin/wait-for.sh", "db:3306", "--", "/docker-entrypoint.sh"]
    ports:
      - 18080:80
      - 18443:443

volumes:
  gpg_volume:
  images_volume:
