version: '3.4'
services:
  passbolt:
    image: passbolt/passbolt:2.13.5-debian
    tty: true
    env_file:
      - env/passbolt.env
    volumes:
      - gpg_volume:/var/www/passbolt/config/gpg
      - images_volume:/var/www/passbolt/webroot/img/public
    tmpfs:
      - /run
    command: ["/usr/bin/wait-for.sh", "-t", "0", "192.168.100.3:3306", "--", "/docker-entrypoint.sh"]
    ports:
      - 18080:80
      - 18443:443

volumes:
  gpg_volume:
  images_volume:
